/*
 * Crypto Tracker
 * This is a API description for Crypto Tracker application.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: norbert.gal97@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.norbertgal.cryptotracker.model

import com.google.gson.annotations.SerializedName

data class Crypto(
        @Transient
        val id: Long?,
        @SerializedName("id")
        val coinMarketCapId: Long?,
        @SerializedName("name")
        val name: String,
        @SerializedName("symbol")
        val symbol: String,
        @SerializedName("max_supply")
        val maxSupply: Long,
        @SerializedName("total_supply")
        val totalSupply: Long,
        @SerializedName("cmc_rank")
        val cmcRank: Int,
        @SerializedName("quote")
        val quote: HashMap<String, Quote>
)