/*
 * Crypto Tracker
 * This is a API description for Crypto Tracker application.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: norbert.gal97@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.norbertgal.cryptotracker.model

import androidx.room.*
import com.google.gson.annotations.SerializedName

@Entity(tableName = "cryptodetails")
data class Crypto (
        @SerializedName("id")
        @PrimaryKey(autoGenerate = false)
        @ColumnInfo(name="coinmarketcapid")
        val coinMarketCapId: Long?,

        @SerializedName("name")
        @ColumnInfo(name="name")
        val name: String,

        @SerializedName("symbol")
        @ColumnInfo(name="symbol")
        val symbol: String,

        @SerializedName("max_supply")
        @ColumnInfo(name="maxsupply")
        val maxSupply: Double,

        @SerializedName("total_supply")
        @ColumnInfo(name="totalsupply")
        val totalSupply: Double,

        @SerializedName("cmc_rank")
        @ColumnInfo(name="cmcrank")
        val cmcRank: Int,

        @SerializedName("quote")
        @ColumnInfo(name="quote")
        val quote: Map<String, Quote>
)