/*
 * Crypto Tracker
 * This is a API description for Crypto Tracker application.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: norbert.gal97@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.norbertgal.cryptotracker.model

import androidx.room.ColumnInfo
import com.google.gson.annotations.SerializedName

data class Quote(
    @SerializedName("price")
    @ColumnInfo(name="price")
    val price: Double,

    @SerializedName("percent_change_1h")
    @ColumnInfo(name="percentchange1h")
    val percentChange1h: Double,

    @SerializedName("percent_change_24h")
    @ColumnInfo(name="percentchange24h")
    val percentChange24h: Double,

    @SerializedName("percent_change_7d")
    @ColumnInfo(name="percentchange7d")
    val percentChange7d: Double,

    @SerializedName("percent_change_30d")
    @ColumnInfo(name="percentchange30d")
    val percentChange30d: Double
)