/*
 * Crypto Tracker
 * This is a API description for Crypto Tracker application.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: norbert.gal97@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.norbertgal.cryptotracker.model

import com.google.gson.annotations.SerializedName
import java.time.LocalDate

data class Status(
    @SerializedName("timestamp")
    val timestamp: String,
    @SerializedName("error_code")
    val errorCode: Int,
    @SerializedName("error_message")
    val errorMessage: String,
    @SerializedName("elapsed")
    val elapsed: Long,
    @SerializedName("creditCount")
    val creditCount: Int,
)